apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
stringData:
  openaiApiKey: {{ .Values.byokSecrets.openaiApiKey }}
  anthropicApiKey: {{ .Values.byokSecrets.anthropicApiKey }}
  stripeSecretKey: {{ .Values.byokSecrets.stripeSecretKey }}
  stripeWebhookSecret: {{ .Values.byokSecrets.stripeWebhookSecret }}
